#! /bin/sh
# /etc/init.d/blah
#

app=$1
port=$3

WORKERS=8
CANTO_DATA=/data/canto
PID_FILE=/var/run/canto-$app-$port

# Carry out specific functions when asked to by the system
case "$2" in
  start)
    (date; cd /usr/local/share/canto; /usr/local/bin/start_server --pid-file=$PID_FILE --port $port -- ./script/canto_start --workers $WORKERS --keepalive-timeout 5 -s Starman --preload) 2>&1 | tee -a $CANTO_DATA/logs/$app.log &
    ;;
  stop)
    pid=`cat $PID_FILE`
    echo stopping $pid
    kill -TERM $pid
    ;;
  restart)
    pid=`cat $PID_FILE`
    echo restarting $pid
    kill -HUP $pid
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0

