#!/bin/sh -

#
### BEGIN INIT INFO
# Provides:          canto-pombe
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: canto pombe
### END INIT INFO
#

exec su -c "/sbin/canto-ctlr pombe $* 7000" pomcur &
