# build with: docker build --squash -f etc/Dockerfile-base -t=pombase/canto-base:v15 .

FROM bitnami/minideb:stretch
MAINTAINER Kim Rutherford <kim@pombase.org>

RUN apt-get update && apt-get upgrade -y && apt-get install -y apt-utils

RUN apt-get install -y ntpdate sqlite3 make tar gzip whiptail gcc g++ wget \
    perl git-core libxml2-dev zlib1g-dev libssl-dev \
    libexpat1-dev libpq-dev curl sendmail \
    libpq-dev libxml2-dev zlib1g-dev libssl-dev libexpat1-dev && apt-get clean

RUN apt-get update; \
  apt-get install -y libcatalyst-perl libcatalyst-modules-perl \
    libserver-starter-perl starman \
    libmodule-install-perl libcatalyst-devel-perl liblocal-lib-perl \
    apt-transport-https ca-certificates && \
   apt-get clean

RUN curl -L http://cpanmin.us | perl - --self-upgrade

RUN echo installing lib lucene && (cd /tmp/; \
  wget https://curation.pombase.org/software/libclucene-dev_0.9.21b-2+b1_amd64.deb && \
  wget https://curation.pombase.org/software/libclucene0ldbl_0.9.21b-2+b1_amd64.deb && \
  dpkg -i libclucene0ldbl_0.9.21b-2+b1_amd64.deb libclucene-dev_0.9.21b-2+b1_amd64.deb && \
  rm libclucene0ldbl_0.9.21b-2+b1_amd64.deb libclucene-dev_0.9.21b-2+b1_amd64.deb)

RUN apt-get -y install openjdk-8-jre-headless

RUN mkdir /tmp/canto
COPY . /tmp/canto/

RUN patch /usr/include/CLucene/store/FSDirectory.h < /tmp/canto/etc/clucene_compilation_fix.patch

RUN cpanm Lucene

RUN (cd /tmp/canto; perl Makefile.PL && make installdeps_notest); rm -rf /tmp/canto

RUN rm -rf /root/.local /root/.cpan*

RUN (cd /usr/local/bin/; curl https://curation.pombase.org/software/owltools > owltools; chmod a+x owltools)

RUN apt-get remove -y gcc g++ && apt-get autoremove -y
