package PomCur::Model::TrackModel;

use strict;
use base 'Catalyst::Model::DBIC::Schema';


=head1 NAME

PomCur::Model::TrackModel - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<PomCur>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<PomCur::TrackDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
