package Canto::Model::TrackModel;

use strict;
use base 'Catalyst::Model::DBIC::Schema';


=head1 NAME

Canto::Model::TrackModel - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Canto>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Canto::TrackDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 LICENSE

Canto is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

=cut

1;
