#!/bin/bash -

if [ ! -d data ]
then
   echo 'missing "data" directory - exiting'
   exit 1
fi

if [ ! -d canto ]
then
   echo 'missing "canto" directory - exiting'
   exit 1
fi

if [ ! -d import_export ]
then
   echo 'missing "import_export" directory - exiting'
   exit 1
fi

if [ ! -d logs ]
then
   echo 'missing "logs" directory - exiting'
   exit 1
fi

EXTRA_ARGS=""

if [ $(uname) = Linux ]
then
    EXTRA_ARGS="--net=host --env=OWLTOOLS_MEMORY"
fi

INTERACTIVE_ARGS="-ti"

if [ $1 = '--non-interactive' ]
then
    shift
    INTERACTIVE_ARGS=""
fi

if [ $1 = '--use-container-name' ]
then
    shift
    CONTAINER_NAME=$1
    shift
    INTERACTIVE_ARGS="$INTERACTIVE_ARGS --name $CONTAINER_NAME"
fi

DOCKER_COMMAND="docker"

if [ $1 = '--use-podman' ]
then
    shift
    DOCKER_COMMAND="podman"
fi

CANTO_DOCKER_RUN_ARGS="$EXTRA_ARGS --rm $INTERACTIVE_ARGS --mount type=bind,source=$(pwd)/logs,target=/logs --mount type=bind,source=$(pwd)/data,target=/data --mount type=bind,source=$(pwd)/import_export,target=/import_export --mount type=bind,source=$(pwd)/canto,target=/canto -w=/canto docker.io/pombase/canto-base:v19"

cd canto

exec $DOCKER_COMMAND run $CANTO_DOCKER_RUN_ARGS "$@"

