#!/bin/bash -

if [ ! -d data ]
then
   echo 'missing "data" directory - exiting'
   exit 1
fi

if [ ! -d canto ]
then
   echo 'missing "canto" directory - exiting'
   exit 1
fi

if [ ! -d import_export ]
then
   echo 'missing "import_export" directory - exiting'
   exit 1
fi

EXTRA_ARGS=""

if [ $(uname) = Linux ]
then
    EXTRA_ARGS=--net=host
fi

CANTO_DOCKER_RUN_ARGS="$EXTRA_ARGS --rm -ti --mount type=bind,source=$(pwd)/data,target=/data --mount type=bind,source=$(pwd)/import_export,target=/import_export --mount type=bind,source=$(pwd)/canto,target=/canto -w=/canto pombase/canto-base:v5"

cd canto

exec docker run -it $CANTO_DOCKER_RUN_ARGS "$@"
