#!/bin/bash -

if [ ! -d data ]
then
   echo 'missing "data" directory - exiting'
   exit 1
fi

if [ ! -d canto ]
then
   echo 'missing "canto" directory - exiting'
   exit 1
fi

if [ ! -d import_export ]
then
   echo 'missing "import_export" directory - exiting'
   exit 1
fi

if [ $(uname) = Linux ]
then
    EXTRA_ARGS="--net=host --env=OWLTOOLS_MEMORY"
fi

if [ "$1" == "--debug" ]; then
    shift
    DEBUG="-e CANTO_DEBUG=TRUE"
fi

TTY_OPT="-t"

if [ "$1" == "--auto" ]; then
    shift
    TTY_OPT=""
fi


CANTO_DOCKER_RUN_ARGS="$EXTRA_ARGS -i $TTY_OPT --rm $DEBUG --security-opt seccomp=unconfined --cap-add=SYS_PTRACE --mount type=bind,source=$(pwd)/data,target=/data --mount type=bind,source=$(pwd)/import_export,target=/import_export --mount type=bind,source=$(pwd)/canto,target=/canto -w=/canto pombase/canto-run:v8"

cd canto

exec docker run $CANTO_DOCKER_RUN_ARGS ./script/canto_start "$@"
