#!/usr/bin/perl

use strict;
use warnings;
use Carp;

use Plack::Runner;
use Plack::Builder;
use Plack::Middleware::ReverseProxy;


BEGIN {
  push @INC, 'lib', '../lib/';
}

use PomCur;

PomCur->setup_engine('PSGI');
my $app = sub { PomCur->run(@_) };

$app = Plack::Middleware::ReverseProxy->wrap($app);

my $runner = Plack::Runner->new;

$runner->parse_options(@ARGV);
$runner->run($app);
