PomCur installation and maintainence.

* Introduction
  PomCur is a generic gene annotation tool with a focus on community curation.
  This document describes PomCur from the adminstrators perspective.
* Requirements
  - Linux, BSD or UNIX
  - Perl
* Getting the code
  Currently the easiest way to get the code is via GitHub.  Run this command
  to get a copy of the code:
#+BEGIN_SRC sh
  git clone git://github.com/kimrutherford/pomcur.git pomcur
#+END_SRC
  This creates a directory called "pomcur".  The directory can be updated
  later with the command:
#+BEGIN_SRC sh
  git pull
#+END_SRC
* Installation
** Debian
   - libfile-copy-recursive-perl
   - libcatalyst-perl
   - libcatalyst-modules-perl
   - libdbd-sqlite3-perl
   - libdbix-class-perl
   - libdbix-class-schema-loader-perl
   - libparams-validate-perl
   - libxml-simple-perl
   - liburi-perl
   - libmodule-install-perl
   - libmoose-perl
* Quick start guide
** Initialising the data directory
   (in the pomcur directory)
   =./script/pomcur_start --init <some_directory>=
** Running the server
   =./script/pomcur_start=
** Visit the application start page
   http://localhost:5000
* Configuration
** =pomcur.yaml=
** Loading data
* Implementation details
** Structure
   There are two parts to the system.

   "Track" run is the part that the adminstrator uses to add people,
   publications and curation sessions to the database.

   "Curs" handles the user curation sessions.
*** Track - user, publication and session tracking
**** Database storage
***** SQLite for main database
*** Curs - curation sessions
    Each curation session has a cooresponding SQLite database.
** Databases
** Database structure
** Code
   PomCur is written in Perl, implemented using the Catalyst framework and
   running on a Plack server.

* Developing PomCur
** Running tests
   :PROPERTIES:
   :ID:       7e75cddc-b9b9-410b-ac68-8900457483ad
   :END:
   In general the tests can be run with: =make test= in the main pomcur
   directory.  If the schema or test genes or ontologies are is changed the
   test data will need to be [[id:7e75cddc-b9b9-410b-ac68-8900457483ad][re-initialised]].
** Helper scripts
   Scripts to help developers:
   - =etc/db_initialise.pl= :: create empty template database from the schemas
        and recreate the database classes in lib/PomCur/TrackDB and
        lib/PomCur/CursDB
   - =etc/test_initialise.pl= :: initialise the test databases in t/data with
        a small number of genes and a mini version of the Gene Ontology
        database
   - =etc/local_initialise.pl= :: create a test instance of PomCur in ./local
** Initialising test data
   :PROPERTIES:
   :ID:       5867435c-b002-4c97-b912-1cf0d5167100
   :END:
   Run the following commands in the pomcur directory to create the test
   database and to populate it with test data:
#+BEGIN_SRC sh
./etc/db_initialise.pl
./etc/test_initialise.pl
#+END_SRC

   That will need to be done each time the schemas or test data change.

   To create a local test instance of PomCur, run =local_initialise.pl=
** Running the test instance
   The server can be run from the top level directory with this command:
#+BEGIN_SRC sh
POMCUR_CONFIG_LOCAL_SUFFIX=local PERL5LIB=lib ./script/pomcur_server.pl -p 5000 -r -d
#+END_SRC
   "5000" is the local port to connect on.  The server should then be
   available at http://localhost:5000/

* Config
###+INFOJS_OPT: view:content toc:t ltoc:t mouse:#dddddd
#+OPTIONS:     H:5
#+STYLE: <style type="text/css">  html { font-family: Times, serif; font-size: 16pt; }</style>
