PomCur installation and maintainence.

* Introduction
  PomCur is a generic gene annotation with a focus on community curation.
  This document describes PomCur from the adminstrators perspective.
* Requirements
  - Linux, BSB or UNIX
  - Perl
* Getting the code
  Currently the easiest way to get the code is via GitHub.  Run this command
  to get a copy of the code:
#+BEGIN_SRC sh
  git clone git://github.com/kimrutherford/pomcur.git pomcur
#+END_SRC
  This creates a directory called "pomcur".  The directory can be updated
  later with the command:
#+BEGIN_SRC sh
  git pull
#+END_SRC
* Installation
** Debian
   - libfile-copy-recursive-perl
   - libcatalyst-perl
   - libcatalyst-modules-perl
   - libdbd-sqlite3-perl
   - libdbix-class-perl
   - libdbix-class-schema-loader-perl
   - libparams-validate-perl
   - libxml-simple-perl
   - liburi-perl
   - libmodule-install-perl
   - libmoose-perl
* Quick start guide
** Initialising the data directory
   (in the pomcur directory)
   =./script/pomcur_start --init <some_directory>=
** Running the server
   =./script/pomcur_start=
** Visit the application start page 
   http://localhost:5000
* Configuration
** =pomcur.yaml=
* Implementation details
** Structure
   There are two parts to the system.

   "Track" run is the part that the adminstrator uses to add people,
   publications and curation sessions to the database.

   "Curs" handles the user curation sessions.
*** Track - user, publication and session tracking
*** Curs - curation sessions
    Each curation session has a cooresponding SQLite database.
** Databases
** Database structure
** Code
   PomCur is written in Perl, implemented using the Catalyst framework and
   running on a Plack server.


###+INFOJS_OPT: view:content toc:t ltoc:t mouse:#dddddd
#+OPTIONS:     H:5
#+STYLE: <style type="text/css">  html { font-family: Times, serif; font-size: 16pt; }</style>
